[2024-11-07 01:14:14 +0000] [3200] [INFO] Starting gunicorn 23.0.0
[2024-11-07 01:14:14 +0000] [3200] [INFO] Listening at: http://0.0.0.0:8080 (3200)
[2024-11-07 01:14:14 +0000] [3200] [INFO] Using worker: sync
[2024-11-07 01:14:14 +0000] [3201] [INFO] Booting worker with pid: 3201
[2024-11-07 02:04:09 +0000] [3201] [WARNING] Invalid request from ip=167.94.145.109: Invalid HTTP Version: (2, 0)
[2024-11-07 03:45:05 +0000] [3200] [CRITICAL] WORKER TIMEOUT (pid:3201)
[2024-11-07 03:45:05 +0000] [3201] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/http/message.py", line 274, in parse
    line, rbuf = self.read_line(unreader, buf, self.limit_request_line)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/http/message.py", line 326, in read_line
    self.get_data(unreader, buf)
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2024-11-07 03:45:05 +0000] [3201] [INFO] Worker exiting (pid: 3201)
[2024-11-07 03:45:06 +0000] [3652] [INFO] Booting worker with pid: 3652
[2024-11-07 03:46:23,333] ERROR in app: Exception on /go [POST]
Traceback (most recent call last):
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/app.py", line 21, in go
    jobStatus = handleGo(data['Job_ID'], data['Client_ID'], data['Database_Length'])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/handleGo.py", line 15, in handleGo
    pubSubSender(i,rowFromDatabase,Job_ID, Client_ID)
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/handleGo.py", line 45, in pubSubSender
    print(future.result())
          ^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/cloud/pubsub_v1/publisher/futures.py", line 66, in result
    return super().result(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/cloud/pubsub_v1/publisher/_batch/thread.py", line 322, in _commit
    response = self._client._gapic_publish(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/cloud/pubsub_v1/publisher/client.py", line 291, in _gapic_publish
    return super().publish(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/pubsub_v1/services/publisher/client.py", line 1067, in publish
    response = rpc(
               ^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
             ^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/api_core/timeout.py", line 120, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.PermissionDenied: 403 Request had insufficient authentication scopes. [reason: "ACCESS_TOKEN_SCOPE_INSUFFICIENT"
domain: "googleapis.com"
metadata {
  key: "service"
  value: "pubsub.googleapis.com"
}
metadata {
  key: "method"
  value: "google.pubsub.v1.Publisher.Publish"
}
]
[2024-11-07 03:46:58,046] ERROR in app: Exception on /go [POST]
Traceback (most recent call last):
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/app.py", line 21, in go
    jobStatus = handleGo(data['Job_ID'], data['Client_ID'], data['Database_Length'])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/handleGo.py", line 15, in handleGo
    pubSubSender(i,rowFromDatabase,Job_ID, Client_ID)
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/handleGo.py", line 45, in pubSubSender
    print(future.result())
          ^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/cloud/pubsub_v1/publisher/futures.py", line 66, in result
    return super().result(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/cloud/pubsub_v1/publisher/_batch/thread.py", line 322, in _commit
    response = self._client._gapic_publish(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/cloud/pubsub_v1/publisher/client.py", line 291, in _gapic_publish
    return super().publish(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/pubsub_v1/services/publisher/client.py", line 1067, in publish
    response = rpc(
               ^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
             ^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/api_core/timeout.py", line 120, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.PermissionDenied: 403 Request had insufficient authentication scopes. [reason: "ACCESS_TOKEN_SCOPE_INSUFFICIENT"
domain: "googleapis.com"
metadata {
  key: "service"
  value: "pubsub.googleapis.com"
}
metadata {
  key: "method"
  value: "google.pubsub.v1.Publisher.Publish"
}
]
[2024-11-07 03:49:07 +0000] [3200] [CRITICAL] WORKER TIMEOUT (pid:3652)
[2024-11-07 03:49:07 +0000] [3652] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/http/message.py", line 274, in parse
    line, rbuf = self.read_line(unreader, buf, self.limit_request_line)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/http/message.py", line 326, in read_line
    self.get_data(unreader, buf)
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2024-11-07 03:49:07 +0000] [3652] [INFO] Worker exiting (pid: 3652)
job43
rick sorkin
13
Error querying BigQuery: 403 Access Denied: BigQuery BigQuery: Missing required OAuth scope. Need BigQuery or Cloud Platform read scope.; reason: accessDenied, message: Access Denied: BigQuery BigQuery: Missing required OAuth scope. Need BigQuery or Cloud Platform read scope.

Location: US
Job ID: e727acf3-9368-45e0-ac00-68c632f0b8cd

job43
rick sorkin
13
Error querying BigQuery: 403 Access Denied: BigQuery BigQuery: Missing required OAuth scope. Need BigQuery or Cloud Platform read scope.; reason: accessDenied, message: Access Denied: BigQuery BigQuery: Missing required OAuth scope. Need BigQuery or Cloud Platform read scope.

Location: US
Job ID: ca116112-69fa-41bf-91df-cdcd44307973

[2024-11-07 03:49:07 +0000] [3677] [INFO] Booting worker with pid: 3677
[2024-11-07 03:53:50 +0000] [3200] [CRITICAL] WORKER TIMEOUT (pid:3677)
[2024-11-07 03:53:50 +0000] [3677] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/http/message.py", line 274, in parse
    line, rbuf = self.read_line(unreader, buf, self.limit_request_line)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/http/message.py", line 326, in read_line
    self.get_data(unreader, buf)
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2024-11-07 03:53:50 +0000] [3677] [INFO] Worker exiting (pid: 3677)
[2024-11-07 03:53:50 +0000] [3679] [INFO] Booting worker with pid: 3679
[2024-11-07 03:55:28 +0000] [3200] [CRITICAL] WORKER TIMEOUT (pid:3679)
[2024-11-07 03:55:28 +0000] [3679] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/http/message.py", line 274, in parse
    line, rbuf = self.read_line(unreader, buf, self.limit_request_line)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/http/message.py", line 326, in read_line
    self.get_data(unreader, buf)
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2024-11-07 03:55:28 +0000] [3679] [INFO] Worker exiting (pid: 3679)
[2024-11-07 03:55:28 +0000] [3681] [INFO] Booting worker with pid: 3681
[2024-11-07 03:55:32,280] ERROR in app: Exception on /go [POST]
Traceback (most recent call last):
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/app.py", line 21, in go
    jobStatus = handleGo(data['Job_ID'], data['Client_ID'], data['Database_Length'])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/handleGo.py", line 15, in handleGo
    pubSubSender(i,rowFromDatabase,Job_ID, Client_ID)
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/handleGo.py", line 45, in pubSubSender
    print(future.result())
          ^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/cloud/pubsub_v1/publisher/futures.py", line 66, in result
    return super().result(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/cloud/pubsub_v1/publisher/_batch/thread.py", line 322, in _commit
    response = self._client._gapic_publish(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/cloud/pubsub_v1/publisher/client.py", line 291, in _gapic_publish
    return super().publish(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/pubsub_v1/services/publisher/client.py", line 1067, in publish
    response = rpc(
               ^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
             ^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/api_core/timeout.py", line 120, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.PermissionDenied: 403 Request had insufficient authentication scopes. [reason: "ACCESS_TOKEN_SCOPE_INSUFFICIENT"
domain: "googleapis.com"
metadata {
  key: "service"
  value: "pubsub.googleapis.com"
}
metadata {
  key: "method"
  value: "google.pubsub.v1.Publisher.Publish"
}
]
[2024-11-07 03:59:10 +0000] [3200] [CRITICAL] WORKER TIMEOUT (pid:3681)
[2024-11-07 03:59:10 +0000] [3681] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/http/message.py", line 274, in parse
    line, rbuf = self.read_line(unreader, buf, self.limit_request_line)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/http/message.py", line 326, in read_line
    self.get_data(unreader, buf)
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2024-11-07 03:59:10 +0000] [3681] [INFO] Worker exiting (pid: 3681)
job43
rick sorkin
13
Error querying BigQuery: 403 Access Denied: BigQuery BigQuery: Missing required OAuth scope. Need BigQuery or Cloud Platform read scope.; reason: accessDenied, message: Access Denied: BigQuery BigQuery: Missing required OAuth scope. Need BigQuery or Cloud Platform read scope.

Location: US
Job ID: 77af8fab-698b-422d-b459-49d072dd9fdd

[2024-11-07 03:59:10 +0000] [3915] [INFO] Booting worker with pid: 3915
[2024-11-07 04:01:44,991] ERROR in app: Exception on /go [POST]
Traceback (most recent call last):
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/app.py", line 21, in go
    jobStatus = handleGo(data['Job_ID'], data['Client_ID'], data['Database_Length'])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/handleGo.py", line 15, in handleGo
    pubSubSender(i,rowFromDatabase,Job_ID, Client_ID)
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/handleGo.py", line 45, in pubSubSender
    print(future.result())
          ^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/cloud/pubsub_v1/publisher/futures.py", line 66, in result
    return super().result(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/cloud/pubsub_v1/publisher/_batch/thread.py", line 322, in _commit
    response = self._client._gapic_publish(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/cloud/pubsub_v1/publisher/client.py", line 291, in _gapic_publish
    return super().publish(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/pubsub_v1/services/publisher/client.py", line 1067, in publish
    response = rpc(
               ^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
             ^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/api_core/timeout.py", line 120, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.PermissionDenied: 403 Request had insufficient authentication scopes. [reason: "ACCESS_TOKEN_SCOPE_INSUFFICIENT"
domain: "googleapis.com"
metadata {
  key: "service"
  value: "pubsub.googleapis.com"
}
metadata {
  key: "method"
  value: "google.pubsub.v1.Publisher.Publish"
}
]
[2024-11-07 04:01:52,479] ERROR in app: Exception on /go [POST]
Traceback (most recent call last):
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/app.py", line 21, in go
    jobStatus = handleGo(data['Job_ID'], data['Client_ID'], data['Database_Length'])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/handleGo.py", line 15, in handleGo
    pubSubSender(i,rowFromDatabase,Job_ID, Client_ID)
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/handleGo.py", line 45, in pubSubSender
    print(future.result())
          ^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/cloud/pubsub_v1/publisher/futures.py", line 66, in result
    return super().result(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/cloud/pubsub_v1/publisher/_batch/thread.py", line 322, in _commit
    response = self._client._gapic_publish(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/cloud/pubsub_v1/publisher/client.py", line 291, in _gapic_publish
    return super().publish(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/pubsub_v1/services/publisher/client.py", line 1067, in publish
    response = rpc(
               ^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
             ^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/api_core/timeout.py", line 120, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.PermissionDenied: 403 Request had insufficient authentication scopes. [reason: "ACCESS_TOKEN_SCOPE_INSUFFICIENT"
domain: "googleapis.com"
metadata {
  key: "service"
  value: "pubsub.googleapis.com"
}
metadata {
  key: "method"
  value: "google.pubsub.v1.Publisher.Publish"
}
]
[2024-11-07 04:02:19,146] ERROR in app: Exception on /go [POST]
Traceback (most recent call last):
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/app.py", line 21, in go
    jobStatus = handleGo(data['Job_ID'], data['Client_ID'], data['Database_Length'])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/handleGo.py", line 15, in handleGo
    pubSubSender(i,rowFromDatabase,Job_ID, Client_ID)
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/handleGo.py", line 45, in pubSubSender
    print(future.result())
          ^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/cloud/pubsub_v1/publisher/futures.py", line 66, in result
    return super().result(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/cloud/pubsub_v1/publisher/_batch/thread.py", line 322, in _commit
    response = self._client._gapic_publish(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/cloud/pubsub_v1/publisher/client.py", line 291, in _gapic_publish
    return super().publish(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/pubsub_v1/services/publisher/client.py", line 1067, in publish
    response = rpc(
               ^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
             ^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/api_core/timeout.py", line 120, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.PermissionDenied: 403 Request had insufficient authentication scopes. [reason: "ACCESS_TOKEN_SCOPE_INSUFFICIENT"
domain: "googleapis.com"
metadata {
  key: "service"
  value: "pubsub.googleapis.com"
}
metadata {
  key: "method"
  value: "google.pubsub.v1.Publisher.Publish"
}
]
[2024-11-07 04:10:09 +0000] [3200] [CRITICAL] WORKER TIMEOUT (pid:3915)
[2024-11-07 04:10:09 +0000] [3915] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/http/message.py", line 274, in parse
    line, rbuf = self.read_line(unreader, buf, self.limit_request_line)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/http/message.py", line 326, in read_line
    self.get_data(unreader, buf)
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2024-11-07 04:10:09 +0000] [3915] [INFO] Worker exiting (pid: 3915)
job43
rick sorkin
13
Error querying BigQuery: 403 Access Denied: BigQuery BigQuery: Missing required OAuth scope. Need BigQuery or Cloud Platform read scope.; reason: accessDenied, message: Access Denied: BigQuery BigQuery: Missing required OAuth scope. Need BigQuery or Cloud Platform read scope.

Location: US
Job ID: 143faa53-aa9e-472b-81ef-c8221c718abc

job43
rick sorkin
13
Error querying BigQuery: 403 Access Denied: BigQuery BigQuery: Missing required OAuth scope. Need BigQuery or Cloud Platform read scope.; reason: accessDenied, message: Access Denied: BigQuery BigQuery: Missing required OAuth scope. Need BigQuery or Cloud Platform read scope.

Location: US
Job ID: 870dc7e9-ce92-47c6-b613-22a6c963555f

job43
rick sorkin
13
Error querying BigQuery: 403 Access Denied: BigQuery BigQuery: Missing required OAuth scope. Need BigQuery or Cloud Platform read scope.; reason: accessDenied, message: Access Denied: BigQuery BigQuery: Missing required OAuth scope. Need BigQuery or Cloud Platform read scope.

Location: US
Job ID: 8ce32e92-9597-4998-8917-712b992fe104

[2024-11-07 04:10:09 +0000] [4255] [INFO] Booting worker with pid: 4255
[2024-11-07 04:10:16,622] ERROR in app: Exception on /go [POST]
Traceback (most recent call last):
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/app.py", line 21, in go
    jobStatus = handleGo(data['Job_ID'], data['Client_ID'], data['Database_Length'])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/handleGo.py", line 15, in handleGo
    pubSubSender(i,rowFromDatabase,Job_ID, Client_ID)
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/handleGo.py", line 45, in pubSubSender
    print(future.result())
          ^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/cloud/pubsub_v1/publisher/futures.py", line 66, in result
    return super().result(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/cloud/pubsub_v1/publisher/_batch/thread.py", line 322, in _commit
    response = self._client._gapic_publish(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/cloud/pubsub_v1/publisher/client.py", line 291, in _gapic_publish
    return super().publish(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/pubsub_v1/services/publisher/client.py", line 1067, in publish
    response = rpc(
               ^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
             ^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/api_core/timeout.py", line 120, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahrobitshek/async-batch-cloud-llms/Batch-Processor/myenv/lib/python3.11/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.PermissionDenied: 403 Request had insufficient authentication scopes. [reason: "ACCESS_TOKEN_SCOPE_INSUFFICIENT"
domain: "googleapis.com"
metadata {
  key: "service"
  value: "pubsub.googleapis.com"
}
metadata {
  key: "method"
  value: "google.pubsub.v1.Publisher.Publish"
}
]
[2024-11-07 06:27:12 +0000] [4255] [WARNING] Invalid request from ip=199.45.155.107: Invalid HTTP Version: (2, 0)
[2024-11-07 08:38:27 +0000] [4255] [WARNING] Invalid request from ip=167.94.146.56: Invalid HTTP Version: (2, 0)
[2024-11-07 16:32:32 +0000] [4255] [WARNING] Invalid request from ip=162.142.125.223: Invalid HTTP Version: (2, 0)
[2024-11-07 18:12:07 +0000] [4255] [INFO] Worker exiting (pid: 4255)
[2024-11-07 18:12:07 +0000] [3200] [INFO] Handling signal: term
job43
rick sorkin
13
Error querying BigQuery: 403 Access Denied: BigQuery BigQuery: Missing required OAuth scope. Need BigQuery or Cloud Platform read scope.; reason: accessDenied, message: Access Denied: BigQuery BigQuery: Missing required OAuth scope. Need BigQuery or Cloud Platform read scope.

Location: US
Job ID: db38bf8a-bfc5-49c3-ac38-e29972a81e8a

[2024-11-07 18:12:07 +0000] [3200] [ERROR] Worker (pid:4255) was sent SIGHUP!
[2024-11-07 18:12:07 +0000] [3200] [INFO] Shutting down: Master
